name: Zac Ioannidis
markdown: kramdown
permalink: /:categories/:title/
exclude: [Gemfile, Gemfile.lock]
excerpt_separator: ""
highlighter: pygments
rdiscount:
  extensions: [smart]
port: 8000
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
